export const DEFAULT = 'DEFAULT';
export const ACCESS_INFO_REQUESTED = 'ACCESS_INFO_REQUESTED';
export const ACCESS_INFO_SUCCESS = 'ACCESS_INFO_SUCCESS';
export const ACCESS_INFO_ERROR = 'ACCESS_INFO_ERROR';
export const ACCESS_INFO_SAVE_REQUESTED = 'ACCESS_INFO_SAVE_REQUESTED';
export const ACCESS_INFO_SAVE_SUCCESS = 'ACCESS_INFO_SAVE_SUCCESS';
