export const EB_TABLE_INITIALIZE = 'EB_TABLE_INITIALIZE';
export const EB_TABLE_DATA_REQUESTED = 'EB_TABLE_DATA_REQUESTED';
export const EB_TABLE_DATA_SUCCESS = 'EB_TABLE_DATA_SUCCESS';
export const EB_TABLE_DATA_ERROR = 'EB_TABLE_DATA_ERROR';
