    export const ADD_USER =  'ADD_USER';
    export const REMOVE_USER =  'REMOVE_USER';
    export const REMOVE_USERS =  'REMOVE_USERS';
    export const GET_USER = 'GET_USER';
    export const GET_USERS = 'GET_USERS';

    export const SAVE_USER_REQUESTED =  'SAVE_USER_REQUESTED';
    export const SAVE_USER_SUCCESS =  'SAVE_USER_SUCCESS';
    export const SAVE_USER_ERROR =  'SAVE_USER_ERROR';

    //Login Action Types below

    export const INITIALIZE = 'GUEST';
    
    export const LOGIN = 'LOGIN';
    export const LOGOUT = 'LOGOUT';
    export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
    export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    export const LOGGED_IN = 'LOGGED_IN';
    export const LOGIN_REJECTED = 'LOGIN_REJECTED';
    export const LOGIN_ERROR = 'LOGIN_ERROR';
    
    export const REGISTERATION_REQUESTED = 'REGISTERATION_REQUESTED';
    export const REGISTERATION_SUCCESS = 'REGISTERATION_SUCCESS';
    export const REGISTERATION_ERROR = 'REGISTERATION_ERROR';

    export const UPLOADING_REQUESTED = 'UPLOADING_REQUESTED';
    export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
    export const UPLOAD_ERROR = 'UPLOAD_ERROR';

    export const EMAIL_CHECK_REQUESTED = 'EMAIL_CHECK_REQUESTED';
    export const EMAIL_CHECK_EXISTS = 'EMAIL_CHECK_EXISTS';
    export const EMAIL_CHECK_DOES_NOT_EXIST = 'EMAIL_CHECK_DOES_NOT_EXIST';
    export const EMAIL_CHECK_ERROR = 'EMAIL_CHECK_ERROR';

    export const ACTIVATION_HASH_VERIFICATION_REQUESTED = 'ACTIVATION_HASH_VERIFICATION_REQUESTED';
    export const ACTIVATION_HASH_VERIFICATION_VERIFIED = 'ACTIVATION_HASH_VERIFICATION_VERIFIED';
    export const ACTIVATION_HASH_VERIFICATION_NOT_FOUND = 'ACTIVATION_HASH_VERIFICATION_NOT_FOUND';
    export const ACTIVATION_HASH_VERIFICATION_ERROR = 'ACTIVATION_HASH_VERIFICATION_ERROR';

    export const PASSWORD_CHANGE_REQUESTED = 'PASSWORD_CHANGE_REQUESTED';
    export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
    export const PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR';

    export const PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED';
    export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
    export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';

    export const REDIRECTED_TO_LOGIN = 'REDIRECTED_TO_LOGIN';

